// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwmn7kWoy_WSJJIjJkkcGbBR_zZ2yYoOI',
    appId: '1:8828578557:web:e3ecf7451b4f825f68ac94',
    messagingSenderId: '8828578557',
    projectId: 'ceng-10021',
    authDomain: 'ceng-10021.firebaseapp.com',
    storageBucket: 'ceng-10021.appspot.com',
    measurementId: 'G-W1VP461V5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3rOVqERqJaXS3GU9K31RI_h-36Al4nVE',
    appId: '1:8828578557:android:8acd822e74a645a668ac94',
    messagingSenderId: '8828578557',
    projectId: 'ceng-10021',
    storageBucket: 'ceng-10021.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZZyatIJSuPLVhKgLkT0kW7RVdl4DWoKA',
    appId: '1:8828578557:ios:01531c2d5978cf6b68ac94',
    messagingSenderId: '8828578557',
    projectId: 'ceng-10021',
    storageBucket: 'ceng-10021.appspot.com',
    iosClientId: '8828578557-pobv2jteol1beqv17q1dvg02q7cd58ke.apps.googleusercontent.com',
    iosBundleId: 'co',
  );
}
